# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\华为家庭存储\多媒体、计算机文件\编程\aes-file-locker\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(486, 343)
        Dialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 30, 401, 261))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Button_OK = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Button_OK.setCheckable(False)
        self.Button_OK.setObjectName("Button_OK")
        self.gridLayout_2.addWidget(self.Button_OK, 2, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 1, 0, 1, 1)
        self.gridWidget = QtWidgets.QWidget(self.gridLayoutWidget)
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_ps = QtWidgets.QLabel(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_ps.setFont(font)
        self.label_ps.setObjectName("label_ps")
        self.gridLayout.addWidget(self.label_ps, 1, 0, 1, 1)
        self.label_un = QtWidgets.QLabel(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_un.setFont(font)
        self.label_un.setObjectName("label_un")
        self.gridLayout.addWidget(self.label_un, 0, 0, 1, 1)
        self.username_input = QtWidgets.QLineEdit(self.gridWidget)
        self.username_input.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.username_input.setPlaceholderText("")
        self.username_input.setObjectName("username_input")
        self.gridLayout.addWidget(self.username_input, 0, 1, 1, 1)
        self.password_input = QtWidgets.QLineEdit(self.gridWidget)
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input.setPlaceholderText("")
        self.password_input.setObjectName("password_input")
        self.gridLayout.addWidget(self.password_input, 1, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 3, 0, 1, 1)
        self.gridLayout_2.addWidget(self.gridWidget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.username_input, self.password_input)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Button_OK.setWhatsThis(_translate("Dialog", "<html><head/><body><p>确认</p></body></html>"))
        self.Button_OK.setText(_translate("Dialog", "OK"))
        self.Button_OK.setShortcut(_translate("Dialog", "Return"))
        self.label_ps.setWhatsThis(_translate("Dialog", "<html><head/><body><p>密码</p></body></html>"))
        self.label_ps.setText(_translate("Dialog", "Password:"))
        self.label_un.setWhatsThis(_translate("Dialog", "<html><head/><body><p>用户名</p></body></html>"))
        self.label_un.setText(_translate("Dialog", "User Name:"))
        self.username_input.setToolTip(_translate("Dialog", "<html><head/><body><p>输入用户名</p></body></html>"))
        self.username_input.setWhatsThis(_translate("Dialog", "<html><head/><body><p>请输入用户名</p></body></html>"))
        self.password_input.setToolTip(_translate("Dialog", "<html><head/><body><p>输入密码</p></body></html>"))
        self.password_input.setWhatsThis(_translate("Dialog", "<html><head/><body><p>请输入密码</p></body></html>"))
        self.checkBox.setToolTip(_translate("Dialog", "<html><head/><body><p>显示密码</p></body></html>"))
        self.checkBox.setWhatsThis(_translate("Dialog", "<html><head/><body><p>显示密码</p></body></html>"))
        self.checkBox.setText(_translate("Dialog", "Show Password"))
